# Generated by Django 2.1.2 on 2018-10-24 16:41

from django.db import migrations, models


def generate_default_users(apps, schema_editor):
    User = apps.get_model('api', 'User')
    user1 = User()
    user1.name = 'cesar'
    user1.email = 'cesar@local.com'
    user1.auth_key = 'ABCDEFGHIJKLMONPQRST'
    user1.save()
    user2 = User()
    user2.name = 'Juan'
    user2.email = 'juan@local.com'
    user2.auth_key = '987654321ABCDEFGHIJK'
    user2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_default_users)
    ]
