# Generated by Django 2.1.2 on 2018-10-30 20:15
from django.db import migrations
from api.models import User


def generate_default_users(apps, schema_editor):
    user1 = User.objects.create_user(username='cesar',
                                    email='cesar@local.com',
                                    password='qwerty')
    user1.name = 'cesar'
    user1.save()
    user2 = User.objects.create_user(username='r2d2',
                                    email='juan@local.com',
                                    password='qwerty')
    user2.name = 'juan'
    user2.save()
    # The system Superuser
    admin = User.objects.create_superuser(username='admin', email='admin@local.com', password='admin')
    admin.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_default_users)
    ]
